### ISSUE TITLE
Inquiry about Empty Tags Field in response of "GET /registries/{registryName}/packages/{packageName} "  and Solution for Accessing Tags in Repositories with a Release Management System

### ISSUE THREAD

**Issue by HassanOnsori** [ecosyste-ms/repos#283]
Hi @andrew,

In examples 1 and 2, when I made the 'GET /registries/{registryName}/packages/{packageName}' API call, I noticed that the 'tags' field, which is supposed to contain a list of tags, was empty. However, when I made the API call to retrieve a list of tags, it returned a valid list. At first, I assumed that the reason for the empty tags list was the number of releases since there were no releases in GitHub (the count was 0). However, in example 3, even though the number of releases in GitHub was also 0, the tags list was not empty.

I would greatly appreciate it if you could kindly explain the reason behind the empty tags field in examples 1 and 2. Additionally, if possible, could you please provide me and @AlexandreDecan with a solution to access the tags of releases for repositories that utilise a release system?

Endpoint:
GET /registries/{registryName}/packages/{packageName} (Retrieve a package by name)

Examples:

1. Package: 1n1t6Sh3ll/trufflehog
   - Number of releases in GitHub: 0
   - Number of tags in GitHub: 35 (latest tag: v3.6.5 on Jun 15, 2022)
   
   Response of the endpoint:
   - "versions_count": 35
   - "versions_url": [link] (contains 35 versions)
   - "tags_count": Not available
   - "tags": []
   - "tags_url": [link] (contains 35 tags)
   - Explanation: No releases, only defined tags

2. Package: PinkDiamond1/lightning
   - Number of releases in GitHub: 0
   - Number of tags in GitHub: 113 (latest tag: v0.10.1 on Aug 9, 2021)
   
   Response of the endpoint:
   - "versions_count": 100
   - "versions_url": [link] (contains 100 versions)
   - "tags_count": 100
   - "tags": []
   - "tags_url": [link] (contains 100 tags)
   - Explanation: No releases, only defined tags

3. Package: Ginxo/github-action-build-chain
   - Number of releases in GitHub: 0
   - Number of tags in GitHub: 38 (latest tag: v2.6.18 on Nov 12, 2021)
   
   Response of the endpoint:
   - "versions_count": 38
   - "versions_url": [link] (contains 38 versions)
   - "tags_count": 38
   - "tags": [contains 38 tags]
   - "tags_url": [link] (contains 38 tags)
   - Explanation: No releases, only defined tags

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/ecosyste-ms/repos/issues/283">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/283/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/283/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
There's no connection between number of releases and number of tags in the pacakges service, it's just that the tags field had not been synced into the packages service, the package versions are loaded from the same source (the repos service).

The whole `repo_metadata` field in each package is essentially a handy cache of data from the repositories service and so may sometimes be a bit out of date, I recommend fetching the full paginated list of tags using the `tags_url` field, but you should be able to get all the info you need from the list of versions, if not that's a bug/feature that should be fixed in the actions support in the packages service.

**Comment by andrew** [comment]
Releases api end point is now available on the repos service, example: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/7474%2FSRC-DataLinter/releases 

Details documented in the same place as the tags api (both very similar endpoints) 

I'm still syncing releases for all action repos, so could take a few hours to finish.

I also plan to link a release to it's tag but I might not get round to that until next week, for now you can look up the tag using `tag_name`, for example, this release (tag_name v1) https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/7474%2FSRC-DataLinter/releases/v1 will have a tag at: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/7474%2FSRC-DataLinter/tags/v1

**Comment by HassanOnsori** [comment]
Thank you so much.

**Comment by AlexandreDecan** [comment]
Thanks @andrew !! ;-) 

If I may suggest something, it would be nice in the documentation of ecosyste.ms to include a relational data model explaining the relations between the various models you have, and the relation between these models and the various endpoints you provide. We're getting more and more familiar with all these endpoints and data, but I guess this can help other people to make awesome things out of your work ;-)

**Comment by andrew** [comment]
Initial sync of releases complete, approx 140k releases in github actions repos

**Comment by HassanOnsori** [comment]
Hi @andrew ,
I wanted to bring to your attention a small issue I've noticed while using the releases API endpoint. It seems that sometimes it's returning duplicated data (7904 releases out of 145676 releases in github actions repos are duplicated). Here are a few examples of repositories where I've encountered this:

Repository: rich-automation/lotto-action
URL: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/rich-automation%2Flotto-action/releases

Repository: PerfAI-Inc/PerfAI-Action
URL: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/PerfAI-Inc/PerfAI-Action/releases

Repository: jge162/Action-Workflows
URL: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/jge162/Action-Workflows/releases

**Comment by andrew** [comment]
@HassanOnsori thanks for reporting, I will fix that up tomorrow

**Comment by andrew** [comment]
Fixed the bug in https://github.com/ecosyste-ms/repos/commit/28316c349e3bb6cab7231c48e1b5670a3df093bc, working on cleaning up the duplicate releases now

**Comment by andrew** [comment]
Data should be cleaned up now, sorry about that

**Comment by HassanOnsori** [comment]
Thank you so much.

**Comment by andrew** [comment]
@HassanOnsori Can this be closed now?

**Comment by HassanOnsori** [comment]
yes, thanks.
