### ISSUE TITLE
docker compose fails

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/repos#337]
After installing docker on Debian 12 following docker installation instructions and running `docker compose up --build` as a normal user in the `repos` repository, I get a `repos-app-1 exited with code 1` error.  See the log below:

```
...
repos-database.service.repos.internal-1  | 2023-09-25 09:22:36.726 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
repos-database.service.repos.internal-1  | 2023-09-25 09:22:36.726 UTC [1] LOG:  listening on IPv6 address "::", port 5432
repos-database.service.repos.internal-1  | 2023-09-25 09:22:36.730 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
repos-database.service.repos.internal-1  | 2023-09-25 09:22:36.734 UTC [21] LOG:  database system was shut down at 2023-09-24 22:11:15 UTC
repos-database.service.repos.internal-1  | 2023-09-25 09:22:36.738 UTC [1] LOG:  database system is ready to accept connections
repos-app-1                              | exec bin/docker-start: exec format error
repos-app-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 3/3
 ✔ Container repos-redis.service.repos.internal-1     Stopped                                                                                                                             0.4s 
 ✔ Container repos-app-1                              Stopped                                                                                                                             0.0s 
 ✔ Container repos-database.service.repos.internal-1  Stopped                                                                                                                             0.5s 
canceled
```

Can you reproduce this error?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/337">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/337/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/337/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
There was an extra newline in docker-start that was causing that error, I've pushed a fix to master. Database config may still need tweaking to get it to launch correctly, I'm still investigating

**Comment by andrew** [comment]
@bzg just pushed another fix and was able to start it

**Comment by bzg** [comment]
Thank you very much!  I managed to launch the app and visit it on http://localhost:3000.

I'm not sure how to check that workers are crawling the forge for data, repos indexed keeps showing 0.

Any hint?

**Comment by andrew** [comment]
@bzg I just realized that the docker-compose config is not set up to run sidekiq at the same time, sorry about that (I deploy the app onto dokku so it's a slightly different setup).

I'll get that added to the docker-compose config file once I've had some lunch 🥪

**Comment by bzg** [comment]
Great, thanks again for the super quick feedback! Bon appétit ☺️
