### ISSUE TITLE
Paginate when loading tags from GitHub graphql api

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/repos#353]
[Page 1](https://repos.ecosyste.ms/api/v1/hosts/github/repositories/codegouvfr%2Fsill-web/tags?page=1&per_page=100) for 100 items works, while [Page 2](https://repos.ecosyste.ms/api/v1/hosts/github/repositories/codegouvfr%2Fsill-web/tags?page=2&per_page=100) does not.

The repo has more than 100 tags.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/353">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/353/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/353/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
Couple things here:

1. I've just changed the behaviour of pagination when it runs out of pages to return an empty list instead of erroring.
2. There's currently only 100 tags in the database for that repo, which is a bug, the graphql query currently doesn't do pagination, but it should do.

**Comment by andrew** [comment]
Fixed in https://github.com/ecosyste-ms/repos/commit/7995beb0fccccb075c5e42d1a9f0f2a0ab38ea79, deploying now, it's going to take a a few weeks to resync all tags for all repos though
