### ISSUE TITLE
Allow to sort tags

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/repos#354]
The API endpoint `/hosts/{hostName}/repositories/{repositoryName}/tags` does not allow to sort tags by date while this would be useful to get e.g. the latest tag.

I'm not sure if other sorting criteria would be useful.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/354">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/354/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/354/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
@bzg I just added sort and order parameters to the tags and releases endpoints: https://github.com/ecosyste-ms/repos/commit/ee07688df17168b47124d264f940acc8c62a0cda

**Comment by bzg** [comment]
Thanks 👌

**Comment by bzg** [comment]
I've test it with https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/codegouvfr%2Fsill-web/tags and I don't see many tags > 5/12/2023 - I suppose this is because metadata are out of sync with GitHub's data?  Just pointing this, in case that helps.

**Comment by andrew** [comment]
@bzg yeah that will be fixed when I tackle https://github.com/ecosyste-ms/repos/issues/353, hopefully this week

**Comment by andrew** [comment]
pagination fix here: https://github.com/ecosyste-ms/repos/commit/7995beb0fccccb075c5e42d1a9f0f2a0ab38ea79 will resync tags for all the codegouvfr repos now
