### ISSUE TITLE
Check against GOVERNANCE.md

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/repos#362]
Some people are working on stabilizing conventions for a `GOVERNANCE.md` file.

See e.g. [the discussion on sustainoss.org](https://discourse.sustainoss.org/t/governance-md-draft-feedback-solicited/1392) and [this draft](https://github.com/open-quantum-safe/oqs-provider/blob/6467f43428ab5bde1586cfb7aaecf0a604dc1e06/GOVERNANCE.md).

Would it be worth in the future checking against `GOVERNANCE.md` files and provide this information through the API, as is currently done for `README.md`? 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/362">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/362/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/362/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
I started tracking the presence of `GOVERNANCE.md` files 5 months ago: https://github.com/ecosyste-ms/repos/blob/main/app/models/repository.rb#L304C4-L304C4 (https://github.com/ecosyste-ms/repos/blame/main/app/models/repository.rb#L304), not every repo may have been resyncing since then but they all eventually will

**Comment by bzg** [comment]
> I started tracking the presence of GOVERNANCE.md files 5 months ago: 
> https://github.com/ecosyste-ms/repos/blob/main/app/models/
> repository.rb#L304C4-L304C4 (https://github.com/ecosyste-ms/repos/
> blame/main/app/models/repository.rb#L304), not every repo may have
> been resyncing since then but they all eventually will

Good to know, thanks!
