### ISSUE TITLE
Add support for forgejo

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/repos#395]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/395">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/395/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/395/pledge.svg">
</picture>
</a>

**Comment by bzg** [comment]
Documentation: https://codeberg.org/api/swagger

**Comment by andrew** [comment]
forgejo is a fork of gitea, which is already supported, we can just make a subclass of https://github.com/ecosyste-ms/repos/blob/main/app/models/hosts/gitea.rb called forgejo to avoid confusion.

**Comment by andrew** [comment]
Added here: https://github.com/ecosyste-ms/repos/commit/58cb45bb8cce070c7a3f89de26ab5bff8876a2a1

**Comment by bzg** [comment]
Thanks for the feedback.  I also suspected that Gitea was already supported.

PS: Perhaps the title of [this issue](https://github.com/ecosyste-ms/repos/issues/45) might be updated to something like "Add more Gitea instances"?
