### ISSUE TITLE
Discover AUTHOR and ROADMAP files

### ISSUE THREAD

**Issue by hjonin** [ecosyste-ms/repos#400]
Hi!

Would it be possible to discover two more repository metadata files, which would be:
- AUTHORS.[txt|md]
- ROADMAP.md
?

Thanks in advance!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/400">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/400/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/400/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
The area of the code that does the special filename detection is over here: https://github.com/ecosyste-ms/repos/blob/main/app/models/repository.rb#L288-L306

**Comment by andrew** [comment]
@hjonin just added support for both into the repos service, it will take quite some time for all existing repos to be updated, but should be instant if you set up a new instance of the repos service.

**Comment by hjonin** [comment]
Hi @andrew ! Sorry again for my late reply and thanks you so much for your quick implementation! We'll be able to test it on our instance :slightly_smiling_face:
