### ISSUE TITLE
Add latest tag infos in summary

### ISSUE THREAD

**Issue by hjonin** [ecosyste-ms/repos#401]
Hi!

In repos, tags seem to be fetched, for instance to be able to switch between file versions. I was wondering, would it be possible to add information (date and annotation) from the *latest* tag in summary?
For instance, for [this repository](https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/codegouvfr%2Freact-dsfr), it could be something like (to be discussed):
```
"latest_tag_pushed_at": "023-11-28T23:14:37.000Z",
"latest_tag": "v0.78.6"
```

Thanks in advance!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/401">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/401/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/401/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
database fields added in https://github.com/ecosyste-ms/repos/commit/15596d5fc8611d3c88be1c6bfe4637b139c015ee

**Comment by andrew** [comment]
Added code to calculate and record latest tag details after syncing and display in API: https://github.com/ecosyste-ms/repos/commit/e546c7a578059ae27c244f5ceb55e79cc48fd850

All that is left to do is update all existing repos that have tags

**Comment by hjonin** [comment]
Awesome! Thank you so mmuch again!
