### ISSUE TITLE
Force synchronisation?

### ISSUE THREAD

**Issue by hjonin** [ecosyste-ms/repos#402]
Hi!

I was wondering, is it possible to force synchronisation of a repository? For instance, [this one](https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/InseeFrLab%2Fonyxia) has not been synced since September 25.
In any case, what is the synchronisation frequency of a repository?

Thanks in advance!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/402">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/402/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/402/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
Just a note that I've not added the `ping` endpoint to the API documentation as it could allow someone to put a lot of extra jobs in the queue if they pinged everything!

**Comment by hjonin** [comment]
Hi! Sorry for my late reply and thank you very much for your answer! Noted :blush: 

(FYI the project mentioned above seemed to be syncing well after pinging it)
