### ISSUE TITLE
Remove hardcoded ecosyste.ms service path in js files

### ISSUE THREAD

**Issue by simkim** [ecosyste-ms/repos#407]
[application.js](app/assets/javascripts/application.js) has hardcoded path to archives.ecosyte.ms

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/407">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/407/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/407/pledge.svg">
</picture>
</a>

**Comment by simkim** [comment]
@andrew suggested improving the data tags to remove the hardcoded domain name.

**Comment by andrew** [comment]
The same code is also present in the packages service

**Comment by andrew** [comment]
@simkim just pushed a fix that wil now use the domain as configured by ENV['ARCHIVES_DOMAIN'], defaulting to `'https://archives.ecosyste.ms'`

**Comment by simkim** [comment]
@andrew thanks, I will try to deploy this version and archives today
