### ISSUE TITLE
What's the definition of`updated_at`?

### ISSUE THREAD

**Issue by jamietanna** [ecosyste-ms/repos#442]
Via https://repos.ecosyste.ms/api/v1/hosts/GitLab.com/repositories/jamietanna%2Fhttptest-openapi:

```json
{
  "full_name": "jamietanna/httptest-openapi",
  "owner": "jamietanna",
  "pushed_at": null,
  "default_branch": "main",
  "last_synced_at": "2023-12-23T03:29:22.160Z",
  "created_at": "2022-05-21T21:07:13.923Z",
  "updated_at": "2023-12-23T03:29:22.161Z",
  "dependencies_parsed_at": "2022-09-11T20:20:42.667Z",
  "html_url": "https://gitlab.com/jamietanna/httptest-openapi",
}
```

The [activity tab on GitLab](https://gitlab.com/jamietanna/httptest-openapi/activity) shows no changes since 2024-01-11, and I can't see any pushes to any branches since then either (via https://gitlab.com/jamietanna/httptest-openapi/-/pipelines)

I can't see any recently added comments, either.

Just wanted to confirm what the definition of the field was - I couldn't see anything in the OpenAPI, but not sure if I've missed some other docs!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ecosyste-ms) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ecosyste-ms/repos/issues/442">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ecosyste-ms/repos/issues/442/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ecosyste-ms/repos/issues/442/pledge.svg">
</picture>
</a>

**Comment by andrew** [comment]
@jamietanna it's whatever comes back from the gitlab api in `last_activity_at`: https://gitlab.com/api/v4/projects/jamietanna%2Fhttptest-openapi

**Comment by jamietanna** [comment]
Interesting. So right now GitLab is showing it as `"2024-01-11T16:50:52.997Z"`, which is probably because the last time the repo scanned was before that activity - so worth following #402 to update it?

**Comment by andrew** [comment]
There could be a bug with the gitlab saving that's causing `updated_at` to not be in sync, but it could be that it's just not been synced recently, I just gave it a ping.

**Comment by andrew** [comment]
Here's the code for the gitlab integration: https://github.com/ecosyste-ms/repos/blob/main/app/models/hosts/gitlab.rb

**Comment by andrew** [comment]
The repos service is definitely struggling to keep up to date with almost 200 million repos at the moment!

**Comment by jamietanna** [comment]
I can imagine 🫣 appreciate the answer, thank you!

Looking to use this, via the Packages API, alongside OpenSSF Scorecards to add some additional insight + information around dependency health

**Comment by andrew** [comment]
Feel free to use the ping endpoint, although if a repo has been synced in the past 24 hours it'll be a no-op, also if the queue if backed up it may take a few hours (gets very backed up during the middle of the american work day)
