### ISSUE TITLE
Gitea and Forgejo support

### ISSUE THREAD

**Issue by MichaelHinrichs** [ecosyste-ms/repos#602]
Why are the git servers except for GitHub, French GitLab servers?

**Comment by andrew** [comment]
I'm slowly adding more git servers, primarily through ones references from https://packages.ecosyste.ms/ which just happen to be lots of french gitlab services, there are also quite a few gitea and forgejo servers: https://repos.ecosyste.ms/hosts/kinds/gitea and https://repos.ecosyste.ms/hosts/kinds/forgejo

I'm looking at using https://www.shodan.io/search?query=http.title%3Aforgejo to find more public git hosts in the future.

If you know of any others that haven't been indexed please let me know and I'll add them
