### ISSUE TITLE
created_at / updated_at overwrite

### ISSUE THREAD

**Issue by simkim** [ecosyste-ms/repos#646]
Hi @andrew 

We have a bug where after a sync_repository, updated_at is set at the last activity. 

But an update of the object trigger rails to set updated_at at the current time.

We have two possibilities :
  - Disable rails automatic update of created_at / updated_at for owner and repos and manually set them from remote info.
  - Create other attributes to separate rails internal info from external one : registered_at / last_activity_at ?
 
I'm willing to implement whatever you prefer.

What do you think ?

**Comment by andrew** [comment]
I prefer the first option, as that doesn't change the existing api schema, and in the past I've tried to avoid getting the automatic rails timestamp updates on records synced from github (because they share the same field names)

**Comment by simkim** [comment]
Yes github and gitlab are coded in rails :)

I will do the first option.

Thanks
